name: Run Tests

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - add-test-action
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      RANDOM_VALUE_TEST_REPLACEMENT: 123

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Start test server in background
        run: npm run test:server &
      - name: Run tests
        run: npm run test
